{"id":"4760","user":{"id":"179794","nickname":"ftxqgfudi","avatar_url":"https://cdn-community.codemao.cn/community_frontend/community_default_avatar/avatar_300x300_01.jpg","subject_id":0,"work_shop_name":"","work_shop_level":0,"wuhan_medal":false,"has_signed":false},"title":"【求助】CMD里面的pip install","content":"<p><p>为什么我无论install什么都提示错误呢？</p>\n<p>pip install pillow</p>\n<p>pip install pyinstaller</p>\n<p>pip install py2exe</p>\n<p>等等等等……</p>\n<p>无论哪个，结果都是报错。</p>\n<p>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last): </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\runpy.py\",&nbsp;line&nbsp;193,&nbsp;in&nbsp;_run_module_as_main </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;\"__main__\",&nbsp;mod_spec) </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\runpy.py\",&nbsp;line&nbsp;85,&nbsp;in&nbsp;_run_code </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;exec(code,&nbsp;run_globals) </p>\n<p>&nbsp;&nbsp;File&nbsp;\"C:\\Users\\于念一\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\pip.exe\\__main__.py\",&nbsp;line&nbsp;5,&nbsp;in&nbsp;&lt;module&gt; </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pip\\__init__.py\",&nbsp;line&nbsp;26,&nbsp;in&nbsp;&lt;module&gt; </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;pip.utils&nbsp;import&nbsp;get_installed_distributions,&nbsp;get_prog </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pip\\utils\\__init__.py\",&nbsp;line&nbsp;27,&nbsp;in&nbsp;&lt;module&gt; </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;pip._vendor&nbsp;import&nbsp;pkg_resources </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pip\\_vendor\\pkg_resources\\__init__.py\",&nbsp;line&nbsp;70,&nbsp;in&nbsp;&lt;module&gt; </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;pip._vendor&nbsp;import&nbsp;appdirs </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pip\\_vendor\\appdirs.py\",&nbsp;line&nbsp;510,&nbsp;in&nbsp;&lt;module&gt; </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;win32com.shell </p>\n<p>&nbsp;&nbsp;File&nbsp;\"c:\\users\\于念一\\appdata\\local\\programs\\python\\python36-32\\lib\\win32com.py\",&nbsp;line&nbsp;73 </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;print&nbsp;\"Connected&nbsp;to&nbsp;%s&nbsp;at&nbsp;%s&nbsp;baud\"&nbsp;%&nbsp;(port,&nbsp;dcb.BaudRate) </p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^ </p>\n<p>SyntaxError:&nbsp;invalid&nbsp;syntax</p>\n<p>上面是全部报错信息。</p>\n<p>高人求教。</p>\n<p><br></p></p>","board_id":"5","board_name":"你问我答","updated_at":1499470331,"created_at":1499389824,"n_views":228,"n_replies":8,"n_comments":0,"is_authorized":false,"is_featured":false,"is_hotted":false,"is_pinned":false,"tutorial_flag":0,"ask_help_flag":0}